# 에러 처리

## 에러 처리의 필요성

- `try ... catch` 문을 사용해 발생한 에러에 적절하게 대응하면 프로그램이 강제 종료되지 않고 계속해서 코드를 실행시킬 수 있음

```js
console.log("[Start]");

try {
  foo();
} catch (error) {
  console.error("[에러 발생]", error);
  // [에러 발생] ReferenceError: foo is not defined
}

// 발생한 에러에 적절한 대응을 하면 프로그램이 강제 종료되지 않는다.
console.log("[End]");
```

## try ... catch ... finally 문

```js
try {
  // 실행할 코드(에러 발생 가능성이 있는 코드)
} catch (err) {
  // try 코드 블록에서 에러가 발생하면 실행됨
  // try 코드 블록에서 발생한 Error 객체가 전달됨
} finally {
  // 에러 발생과 상관없이 반드시 한 번 실행
}
```

## Error 객체

- Error 생성자 함수는 에러 객체를 생성함
- 에러를 상세히 설명하는 에러 메시지를 인수로 전달할 수 있음

```js
const error = new Error("invaild");
```

## throw 문

- 에러 객체 생성과 에러 발생은 의미가 다름
- 에러를 발생시키려면 try 코드 블록에서 throw 문으로 에러 객체를 던져야 함

```js
try {
  // 에러 객체를 던지면 catch 코드 블록이 실행되기 시작한다.
  throw new Error("something wrong");
} catch (error) {
  console.log(error);
}
```
